name: get secrets
on: push
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FIRST_NAME: Mona
  LAST_NAME: Octocat
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: My first action
        run: echo 'Hi ${{ env.LAST_NAME }}' 

      - name: echo a string
        run: echo "Hello World"